stages:
  - check
  - build

check:
  stage: check
  image: rust:latest
  script:
    - cargo check --verbose
    - cargo test --verbose

build:
  stage: build
  image: rust:latest
  artifacts:
    paths:
      - target/release/compile_map_json
      - target/release/svg_splitter
      - target/release/map_drawer
  script:
    - cargo build --release --features=compile_map_json,svg_splitter,map_drawer
